### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by caugner**
This PR adds the German locale for the discourse-narrative-bot.

### CODE REVIEW

**Comment by tgxworld** [comment]
Thank you @caugner  and @gschlager  :+1: Let me know once you're finished the translation and remember to squash your commits :wink:

**Comment by gschlager** [comment]
@tgxworld I'll let you know. I want to review it first and, of course, I'll squash the commits. 😉

**Comment by caugner** [comment]
@tgxworld Is squash merging disabled in this repo? I usually prefer this, because squashing the PR branch itself loses comments on individual commits afaik.

**Comment by tgxworld** [comment]
I can squash and merge. This is fine. :+1:

**Comment by tgxworld** [comment]
Let me know when this is ready :+1:

**Comment by gschlager** [comment]
@tgxworld This is now ready to be merged. 😉

**Comment by tgxworld** [comment]
Thank you so much @gschlager  and @caugner  :+1:

**Pull request merged**
