### PR TITLE
Initial version for server.es.yml

### PR DESCRIPTION
**Pull request by SidVal**
:es: Initial version, when I finish it, I'll upload the final version (in spanish)

### CODE REVIEW

**Comment by tgxworld** [comment]
HI @SidVal, we're still making alot of changes to discobot at the moment so I'll hold off merging this for now. Thank you for taking the time to submit a translation though!

**Comment by SidVal** [comment]
All right @tgxworld, just give me a mention when you think is stable to translate it :blush:

**Comment by tgxworld** [comment]
Hi @SidVal :) The plugin is ready to be translated hehe

**Comment by SidVal** [comment]
Ok, give me some time to compare and translate :+1:

**Comment by SidVal** [comment]
@tgxworld , excuse me... at [L196](https://github.com/discourse/discourse-narrative-bot/blob/master/config/locales/server.en.yml#L196) said: `capy&#8203;bara`
It's "capybara" the english word, isn't it? (https://en.wikipedia.org/wiki/Capybara)

**Comment by SidVal** [comment]
Done @tgxworld  :arrow_right:  https://github.com/discourse/discourse-narrative-bot/pull/3

**Pull request closed without merging**
